name: Daily Scraper

on:
  push:
    branches:
      - master
  schedule:
    # Run at 12 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Check for changes in scraped_data.json and images/
        id: git-status
        run: |
          git add scraped_data.json images/
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "::set-output name=changes-detected::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes-detected::true"
          fi

      - name: Commit changes
        if: steps.git-status.outputs.changes-detected == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout gh-pages
          git merge main --no-edit
          git add scraped_data.json images/
          git commit -m "Update scraped data and images."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        if: steps.git-status.outputs.changes-detected == 'true'
        run: |
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
