name: Daily Scraper

on:
  push:
    branches:
      - master
  schedule:
    # Run at 12 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Check for changes in scraped_data.json and images/
        id: git-status
        run: |
          git add scraped_data.json images/
          if git diff --cached --quiet; then
            echo "changes-detected=false" >> $GITHUB_ENV
          else
            echo "changes-detected=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.changes-detected == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git merge master --allow-unrelated-histories --no-edit
          else
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit"
            git push origin gh-pages
            git checkout master
            git merge gh-pages --allow-unrelated-histories --no-edit
            git checkout gh-pages
          fi
          git add scraped_data.json images/
          git commit -m "Update scraped data and images."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        if: env.changes-detected == 'true'
        run: |
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
