name: Daily Scraper

on:
  push:
    branches:
      - master
  schedule:
    # Run at 12 AM UTC every day
    - cron: "0 0 * * *"
    # Run at 12 PM UTC every day
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Check for changes in scraped_data.json and images/
        id: git-status
        run: |
          git add scraped_data.json images/
          if git diff --cached --quiet; then
            echo "changes-detected=false" >> $GITHUB_ENV
          else
            echo "changes-detected=true" >> $GITHUB_ENV
          fi

      - name: Prepare deployment directory
        if: env.changes-detected == 'true'
        run: |
          mkdir gh-pages
          cp index.html gh-pages/
          cp scraped_data.json gh-pages/
          cp -r images gh-pages/

      - name: Deploy to GitHub Pages
        if: env.changes-detected == 'true'
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: gh-pages
          keep_files: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          publish_branch: gh-pages
          full_commit_message: "Update scraped data and images."
